/**
 * Mock Books Data
 * Sample books for the store system
 */

import { Book, BookPackage, PaymentMethod } from "@/types/store";

export const MOCK_BOOKS: Book[] = [
  {
    id: "book-1",
    title: "Al-Liwa Package - Term 1 - Grade 1",
    titleAr: "باكيدج اللواء الترم الأول - ١ ثانوي",
    description:
      "Comprehensive Arabic language package for first year secondary students",
    descriptionAr: "باكيدج شامل للغة العربية للصف الأول الثانوي - الترم الأول",
    author: "Mr. Reda El Farouk",
    authorAr: "الأستاذ رضا الفاروق",
    price: 180,
    currency: "EGP",
    grade: "1",
    subject: "Arabic Language",
    subjectAr: "اللغة العربية",
    category: "package",
    categoryAr: "باكيدج",
    coverImage: "/books/liwa-grade1-term1.jpg",
    images: ["/books/liwa-grade1-term1.jpg"],
    pages: 350,
    publisher: "Al-Liwa Publishing",
    publisherAr: "دار اللواء للنشر",
    publishDate: "2024-09-01",
    edition: "2024/2025",
    language: "ar",
    format: "physical",
    stock: 150,
    inStock: true,
    featured: true,
    bestseller: true,
    newArrival: false,
    rating: 4.9,
    reviewCount: 247,
    weight: 0.8,
    dimensions: { length: 28, width: 21, height: 2 },
    tags: ["grammar", "rhetoric", "literature", "comprehensive"],
    tagsAr: ["نحو", "بلاغة", "أدب", "شامل"],
    createdAt: "2024-09-01T00:00:00Z",
    updatedAt: "2024-09-01T00:00:00Z",
  },
  {
    id: "book-2",
    title: "Al-Liwa Package - Term 1 - Grade 2",
    titleAr: "باكيدج اللواء الترم الأول - ٢ ثانوي",
    description:
      "Comprehensive Arabic language package for second year secondary students",
    descriptionAr: "باكيدج شامل للغة العربية للصف الثاني الثانوي - الترم الأول",
    author: "Mr. Reda El Farouk",
    authorAr: "الأستاذ رضا الفاروق",
    price: 180,
    currency: "EGP",
    grade: "2",
    subject: "Arabic Language",
    subjectAr: "اللغة العربية",
    category: "package",
    categoryAr: "باكيدج",
    coverImage: "/books/liwa-grade2-term1.jpg",
    images: ["/books/liwa-grade2-term1.jpg"],
    pages: 380,
    publisher: "Al-Liwa Publishing",
    publisherAr: "دار اللواء للنشر",
    publishDate: "2024-09-01",
    edition: "2024/2025",
    language: "ar",
    format: "physical",
    stock: 120,
    inStock: true,
    featured: true,
    bestseller: true,
    newArrival: false,
    rating: 4.8,
    reviewCount: 198,
    weight: 0.9,
    dimensions: { length: 28, width: 21, height: 2.2 },
    tags: ["grammar", "rhetoric", "literature", "comprehensive"],
    tagsAr: ["نحو", "بلاغة", "أدب", "شامل"],
    createdAt: "2024-09-01T00:00:00Z",
    updatedAt: "2024-09-01T00:00:00Z",
  },
  {
    id: "book-3",
    title: "Al-Liwa Package - Term 1 - Grade 3",
    titleAr: "باكيدج اللواء الترم الأول - ٣ ثانوي",
    description:
      "Comprehensive Arabic language package for third year secondary students - Thanawiya Amma",
    descriptionAr:
      "باكيدج شامل للغة العربية للصف الثالث الثانوي - الثانوية العامة",
    author: "Mr. Reda El Farouk",
    authorAr: "الأستاذ رضا الفاروق",
    price: 250,
    currency: "EGP",
    grade: "3",
    subject: "Arabic Language",
    subjectAr: "اللغة العربية",
    category: "package",
    categoryAr: "باكيدج",
    coverImage: "/books/liwa-grade3-term1.jpg",
    images: ["/books/liwa-grade3-term1.jpg"],
    pages: 450,
    publisher: "Al-Liwa Publishing",
    publisherAr: "دار اللواء للنشر",
    publishDate: "2024-09-01",
    edition: "2024/2025",
    language: "ar",
    format: "physical",
    stock: 200,
    inStock: true,
    featured: true,
    bestseller: true,
    newArrival: false,
    rating: 5.0,
    reviewCount: 412,
    weight: 1.0,
    dimensions: { length: 28, width: 21, height: 2.5 },
    tags: [
      "grammar",
      "rhetoric",
      "literature",
      "comprehensive",
      "thanawiya-amma",
    ],
    tagsAr: ["نحو", "بلاغة", "أدب", "شامل", "ثانوية عامة"],
    createdAt: "2024-09-01T00:00:00Z",
    updatedAt: "2024-09-01T00:00:00Z",
  },
  {
    id: "book-4",
    title: "Grammar Workbook - Grade 1",
    titleAr: "كتاب النحو - الصف الأول الثانوي",
    description: "Comprehensive grammar workbook with exercises and examples",
    descriptionAr: "كتاب شامل للنحو مع تمارين وأمثلة تطبيقية",
    author: "Mr. Reda El Farouk",
    authorAr: "الأستاذ رضا الفاروق",
    price: 80,
    currency: "EGP",
    grade: "1",
    subject: "Grammar",
    subjectAr: "النحو",
    category: "workbook",
    categoryAr: "كتاب تمارين",
    coverImage: "/books/grammar-grade1.jpg",
    images: ["/books/grammar-grade1.jpg"],
    pages: 180,
    publisher: "Al-Liwa Publishing",
    publisherAr: "دار اللواء للنشر",
    publishDate: "2024-09-01",
    edition: "2024/2025",
    language: "ar",
    format: "physical",
    stock: 80,
    inStock: true,
    featured: false,
    bestseller: false,
    newArrival: true,
    rating: 4.7,
    reviewCount: 89,
    weight: 0.4,
    dimensions: { length: 24, width: 17, height: 1.2 },
    tags: ["grammar", "exercises", "workbook"],
    tagsAr: ["نحو", "تمارين", "كتاب تدريبات"],
    createdAt: "2024-09-15T00:00:00Z",
    updatedAt: "2024-09-15T00:00:00Z",
  },
  {
    id: "book-5",
    title: "Rhetoric Guide - Grade 2",
    titleAr: "دليل البلاغة - الصف الثاني الثانوي",
    description: "Complete guide to Arabic rhetoric with modern examples",
    descriptionAr: "دليل شامل للبلاغة العربية مع أمثلة معاصرة",
    author: "Mr. Reda El Farouk",
    authorAr: "الأستاذ رضا الفاروق",
    price: 95,
    currency: "EGP",
    grade: "2",
    subject: "Rhetoric",
    subjectAr: "البلاغة",
    category: "textbook",
    categoryAr: "كتاب مدرسي",
    coverImage: "/books/rhetoric-grade2.jpg",
    images: ["/books/rhetoric-grade2.jpg"],
    pages: 220,
    publisher: "Al-Liwa Publishing",
    publisherAr: "دار اللواء للنشر",
    publishDate: "2024-09-01",
    edition: "2024/2025",
    language: "ar",
    format: "physical",
    stock: 65,
    inStock: true,
    featured: false,
    bestseller: false,
    newArrival: true,
    rating: 4.6,
    reviewCount: 67,
    weight: 0.5,
    dimensions: { length: 24, width: 17, height: 1.5 },
    tags: ["rhetoric", "balagha", "textbook"],
    tagsAr: ["بلاغة", "كتاب مدرسي"],
    createdAt: "2024-09-15T00:00:00Z",
    updatedAt: "2024-09-15T00:00:00Z",
  },
  {
    id: "book-6",
    title: "Literature Anthology - Grade 3",
    titleAr: "مختارات الأدب - الصف الثالث الثانوي",
    description: "Selected literary texts with analysis and commentary",
    descriptionAr: "نصوص أدبية مختارة مع التحليل والشرح",
    author: "Mr. Reda El Farouk",
    authorAr: "الأستاذ رضا الفاروق",
    price: 110,
    currency: "EGP",
    grade: "3",
    subject: "Literature",
    subjectAr: "الأدب",
    category: "textbook",
    categoryAr: "كتاب مدرسي",
    coverImage: "/books/literature-grade3.jpg",
    images: ["/books/literature-grade3.jpg"],
    pages: 280,
    publisher: "Al-Liwa Publishing",
    publisherAr: "دار اللواء للنشر",
    publishDate: "2024-09-01",
    edition: "2024/2025",
    language: "ar",
    format: "physical",
    stock: 95,
    inStock: true,
    featured: false,
    bestseller: true,
    newArrival: false,
    rating: 4.9,
    reviewCount: 156,
    weight: 0.6,
    dimensions: { length: 24, width: 17, height: 1.8 },
    tags: ["literature", "adab", "anthology", "thanawiya-amma"],
    tagsAr: ["أدب", "مختارات", "ثانوية عامة"],
    createdAt: "2024-09-01T00:00:00Z",
    updatedAt: "2024-09-01T00:00:00Z",
  },
];

export const MOCK_PACKAGES: BookPackage[] = [
  {
    id: "package-1",
    title: "Complete Grade 1 Package",
    titleAr: "الباكيدج الكامل - الصف الأول الثانوي",
    description: "All books needed for Grade 1 secondary - both terms",
    descriptionAr: "جميع الكتب المطلوبة للصف الأول الثانوي - الترمين",
    books: [MOCK_BOOKS[0], MOCK_BOOKS[3]],
    price: 240,
    originalPrice: 260,
    discount: 20,
    currency: "EGP",
    grade: "1",
    coverImage: "/packages/grade1-complete.jpg",
    featured: true,
    bestseller: true,
    stock: 50,
    inStock: true,
    createdAt: "2024-09-01T00:00:00Z",
    updatedAt: "2024-09-01T00:00:00Z",
  },
  {
    id: "package-2",
    title: "Complete Grade 2 Package",
    titleAr: "الباكيدج الكامل - الصف الثاني الثانوي",
    description: "All books needed for Grade 2 secondary - both terms",
    descriptionAr: "جميع الكتب المطلوبة للصف الثاني الثانوي - الترمين",
    books: [MOCK_BOOKS[1], MOCK_BOOKS[4]],
    price: 260,
    originalPrice: 275,
    discount: 15,
    currency: "EGP",
    grade: "2",
    coverImage: "/packages/grade2-complete.jpg",
    featured: true,
    bestseller: true,
    stock: 45,
    inStock: true,
    createdAt: "2024-09-01T00:00:00Z",
    updatedAt: "2024-09-01T00:00:00Z",
  },
  {
    id: "package-3",
    title: "Thanawiya Amma Complete Package",
    titleAr: "باكيدج الثانوية العامة الكامل",
    description: "Everything you need for Thanawiya Amma success",
    descriptionAr: "كل ما تحتاجه للنجاح في الثانوية العامة",
    books: [MOCK_BOOKS[2], MOCK_BOOKS[5]],
    price: 340,
    originalPrice: 360,
    discount: 20,
    currency: "EGP",
    grade: "3",
    coverImage: "/packages/grade3-complete.jpg",
    featured: true,
    bestseller: true,
    stock: 75,
    inStock: true,
    createdAt: "2024-09-01T00:00:00Z",
    updatedAt: "2024-09-01T00:00:00Z",
  },
];

export const PAYMENT_METHODS: PaymentMethod[] = [
  {
    id: "cod",
    type: "cash_on_delivery",
    name: "Cash on Delivery",
    nameAr: "الدفع عند الاستلام",
    description: "Pay when you receive your order",
    descriptionAr: "ادفع عند استلام طلبك",
    icon: "Banknote",
    enabled: true,
    fees: 0,
  },
  {
    id: "fawry",
    type: "fawry",
    name: "Fawry",
    nameAr: "فوري",
    description: "Pay through Fawry network",
    descriptionAr: "الدفع من خلال شبكة فوري",
    icon: "Wallet",
    enabled: true,
    fees: 5,
  },
  {
    id: "vodafone",
    type: "vodafone_cash",
    name: "Vodafone Cash",
    nameAr: "فودافون كاش",
    description: "Pay with Vodafone Cash",
    descriptionAr: "الدفع بواسطة فودافون كاش",
    icon: "Smartphone",
    enabled: true,
    fees: 0,
  },
  {
    id: "card",
    type: "credit_card",
    name: "Credit/Debit Card",
    nameAr: "بطاقة ائتمان",
    description: "Pay with Visa or Mastercard",
    descriptionAr: "الدفع ببطاقة فيزا أو ماستركارد",
    icon: "CreditCard",
    enabled: true,
    fees: 0,
  },
  {
    id: "bank",
    type: "bank_transfer",
    name: "Bank Transfer",
    nameAr: "تحويل بنكي",
    description: "Transfer to our bank account",
    descriptionAr: "التحويل إلى حسابنا البنكي",
    icon: "Building",
    enabled: true,
    fees: 0,
  },
];
